// var musicGenres = [
//   {text: 'Alternative'},
//   'Ambient',
//   'Anime',
//   'Blues',
//   'Children’s Music',
//   'Classical',
//   'Comedy',
//   'Commercial',
//   'Country',
//   'Dance',
//   'Disney',
//   'Easy Listening',
//   'Electronic',
//   'Enka',
//   'French Pop',
//   'German Folk',
//   'German Pop',
//   'Fitness & Workout',
//   'Hip-Hop/Rap',
//   'Holiday',
//   'Indie Pop',
//   'Industrial',
//   'Inspirational – Christian & Gospel',
//   'Instrumental',
//   'J-Pop',
//   'Jazz',
//   'K-Pop',
//   'Karaoke',
//   'Kayokyoku',
//   'Latin',
//   'New Age',
//   'Opera',
//   'Polish Folk',
//   'Polish Rock',
//   'Pop',
//   'R&B/Soul',
//   'Reggae',
//   'Rock',
//   'Soundtrack',
//   'Tex-Mex',
//   'Vocal',
//   'World'
// ]

// module.exports = musicGenres
